// generated by stringer -type=ContentType -output=enums-gen.go; DO NOT EDIT

package dispatch

import "fmt"

const _ContentType_name = "BytesTextProtoBuf"

var _ContentType_index = [...]uint8{5, 9, 17}

func (i ContentType) String() string {
	i -= 1
	if i < 0 || i >= ContentType(len(_ContentType_index)) {
		return fmt.Sprintf("ContentType(%d)", i+1)
	}
	hi := _ContentType_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _ContentType_index[i-1]
	}
	return _ContentType_name[lo:hi]
}
